config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'blog#index'
  get 'index' => 'blog#index', as:'blog'
  get 'show/:id' => 'blog#show', as:'blogs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    # controller method that will access the items from the database
    # in the index method we are making an active record call that will save all the contant from the database as an instance variable
    
    def index
       @blog = Blog.all
    end 
    
    def show
        @blog = Blog.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
<h1>post-it-blog</h1>
    <ul>
        <% @blog.each do |b| %>
        <li> <%= link_to b.title, blogs_path(b) %> </li>
        <% end %>
    </ul

app/views/blog/show.html.erb
<h1> <%= @blog.title %> </h1>
<p> <%= @blog.content %> </p>
<p>
    <%= link_to 'All the Blogz', blog_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>